In [2]:
import numpy as np


In [ ]:
a = np.array([1,45,78,90])
b = np.diag(a) # Diagonal positions पर custom values set करता है।

print(b)

[[ 1  0  0  0]
 [ 0 45  0  0]
 [ 0  0 78  0]
 [ 0  0  0 90]]
