In [42]:
import numpy as np


In [43]:
a = np.array([1,45,78,90])
b = np.diag(a) # Diagonal positions पर custom values set करता है।

print(b)

[[ 1  0  0  0]
 [ 0 45  0  0]
 [ 0  0 78  0]
 [ 0  0  0 90]]


In [44]:
a =np.arange(1,5)
a

array([1, 2, 3, 4])

In [45]:
a**2

array([ 1,  4,  9, 16])

In [46]:
a**3

array([ 1,  8, 27, 64])

In [47]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [48]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [50]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

LineSpace() --> It will Return Same Gap Values In A Given Range

In [51]:
a = np.linspace(1,2,5)
a 

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
# Unique() --> It Will Return 3 Arrarys
# Arr --> Return Original Values Of Arrary
# Return_Index = True --> Return Return Index value of unique numbers
# Return_Counts = True --> It will Return Total Frequency of each unique value

In [53]:
a =np.array([1,2,3,2,2,2,4,5])
a

array([1, 2, 3, 2, 2, 2, 4, 5])

In [54]:
np.unique(a ,return_index= True , return_counts= True)


(array([1, 2, 3, 4, 5]), array([0, 1, 2, 6, 7]), array([1, 4, 1, 1, 1]))

In [55]:
# hstack() and vstack()
# hstack() --> it will add 2 or more arrays in horizontally.
# vstack() --> It Will add 2 or more arrays in vertically

In [56]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)
a,b,c

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [57]:
np.hstack((a,b,c))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [58]:
np.vstack((a,b,c))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.random.seed(2)
a = np.random.randint(30,80,36).reshape(2,18)
b = np.random.randint(30,80,36).reshape(4,9)
c = np.random.randint(30,80,36).reshape(6,6)
print(a)


[[70 45 75 38 52 73 48 41 70 37 64 79 61 41 51 77 61 56]
 [50 67 69 33 68 34 72 73 69 68 72 63 33 35 54 34 76 36]]


In [89]:
print(b)

[[61 49 61 32 46 76 42 34 56]
 [45 79 69 76 38 75 45 71 75]
 [38 47 52 39 71 76 56 49 62]
 [73 62 56 38 42 40 70 64 39]]


In [92]:
print(c)

[[67 36 52 36 49 48]
 [31 34 70 47 36 67]
 [63 48 50 56 53 52]
 [73 67 40 38 56 65]
 [57 62 46 51 73 59]
 [46 70 36 40 67 47]]


In [ ]:
# array --> [6,10] , [11,15] --> Combine Horizontally

a = np.arange(6,10)
b = np.arange(11,15)
print(np.hstack((a,b)))


[ 6  7  8  9 11 12 13 14]
