In [17]:
print("Pratice Day Of Numpy ")

Pratice Day Of Numpy 


In [18]:
import numpy as np 


In [19]:
a= np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [20]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.size(a) # It Will Return's the total number_of elements

9

In [22]:
np.shape(a) # It Will Return's the Matrix

(3, 3)

In [23]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a= np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a= np.eye(3) #It Will Return the diagional elements 1,1,1
a 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
b = np.array([1,2,3,4,5,6,7,8])
a = np.diag(b)
a

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [27]:
c = np.random.rand(3) # Ye Random Number's Generate Krta hai But 0-1 ki range me hi 
c

array([0.02592623, 0.54966248, 0.43532239])

In [28]:
d = np.random.randint(1,10,4) # it will Give the random numbers between your range and you Need
print(d)

[9 8 3 2]


In [29]:
np.random.seed(2) # Ye Random Generated Numbers Ko Fix Kr Deta Hai 
x = np.random.randint(1,1010,2)
x

array([169, 528], dtype=int32)

In [30]:
d = np.linspace(1,10,5) # ye same gap ki values generate krta hai  Aapki di Hui Range Me 
d

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
x = np.array([1,2,2,2,2,3,3,4,4,5,5,6,6,6])
d = np.unique(x, return_index= True , return_counts= True)
d

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  5,  7,  9, 11]),
 array([1, 4, 2, 2, 2, 3]))

In [32]:
a = np.array([1,2])
b= np.array([3,4])
c =np.array([5,6])
aa = np.vstack((a,b,c))
bb = np.hstack((a,b,c))
print(aa )
print(bb)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
