In [12]:
print("Hello World !")

Hello World !


In [2]:
import numpy as np 

In [14]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
b = np.arange(1,10,4)
b

array([1, 5, 9])

In [16]:
c = np.random.randint(1,11,4)
print(c)

[2 9 8 9]


In [19]:
np.random.seed(4)
a = np.random.randint(1,10,2)
print(a)

[8 6]
